library(ggplot2)
library(dplyr)
library(scales)

figdata <- read.csv('00.data/03.preds_2014-2019.csv',header = T)
head(figdata)
str(figdata)
figdata$date <- as.Date(figdata$date,origin = '1900-1-1')

tha <- filter(figdata, country == 'Thailand')
lao <- filter(figdata, country == 'Laos')
vie <- filter(figdata, country == 'Vietnam')
cam <- filter(figdata, country == 'Cambodia')
phi <- filter(figdata, country == 'Philippines')
sig <- filter(figdata, country == 'Singapore')
mal <- filter(figdata, country == 'Malaysia')
bel <- filter(figdata, country == 'Belize')
bol <- filter(figdata, country == 'Bolivia')
bra <- filter(figdata, country == 'Brazil')
col <- filter(figdata, country == 'Colombia')
cos <- filter(figdata, country == 'Costa Rica')
dom <- filter(figdata, country == 'Dominican Republic')
ecu <- filter(figdata, country == 'Ecuador')
els <- filter(figdata, country == 'El Salvador')
gua <- filter(figdata, country == 'Guatemala')
hon <- filter(figdata, country == 'Honduras')
jam <- filter(figdata, country == 'Jamaica')
mex <- filter(figdata, country == 'Mexico')
nic <- filter(figdata, country == 'Nicaragua')
pan <- filter(figdata, country == 'Panama')
per <- filter(figdata, country == 'Peru')
ven <- filter(figdata, country == 'Venezuela')

pdf("02.fig/Fig_S19/Fig_S19.pdf", width=15, height=15)

p1 <- ggplot(data = tha) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3), legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) +xlab('') + ylab('') + 
  ggtitle('Thailand') 
p2 <- ggplot(data = lao) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3), legend.position = '', axis.title = element_text(family = 'sans',size = 16), plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Laos')
p3 <- ggplot(data = vie) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') +  theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3), legend.position = '', axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Vietnam')
p4 <- ggplot(data = cam) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') +  theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3), legend.position = '', axis.title = element_text(family = 'sans',size = 16), plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Cambodia')
p5 <- ggplot(data = phi) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3), legend.position = '', axis.title = element_text(family = 'sans',size = 16), plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Philippines')
p6 <- ggplot(data = sig) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3),legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Singapore')
p7 <- ggplot(data = mal) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3),legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Malaysia')
p8 <- ggplot(data = bel) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3),legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Belize')
p9 <- ggplot(data = bol) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3),legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Bolivia')
p10 <- ggplot(data = bra) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3),legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Brazil')
p11 <- ggplot(data = col) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3),legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Colombia')
p12 <- ggplot(data = cos) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3),legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Costa Rica')
p13 <- ggplot(data = dom) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3),legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 14)) + xlab('') + ylab('') + 
  ggtitle('Dominican\nRepublic')
p14 <- ggplot(data = ecu) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3),legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Ecuador')
p15 <- ggplot(data = els) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3),legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('El Salvador')
p16 <- ggplot(data = gua) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3),legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Guatemala')
p17 <- ggplot(data = hon) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3),legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Honduras')
p18 <- ggplot(data = jam) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3),legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Jamaica')
p19 <- ggplot(data = mex) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3),legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Mexico')
p20 <- ggplot(data = nic) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3),legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Nicaragua')
p21 <- ggplot(data = pan) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3),legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Panama')
p22 <- ggplot(data = per) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3),legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Peru')
p23 <- ggplot(data = ven) + geom_line(mapping = aes(x = date, y = pre),lwd = 1.2) + geom_ribbon(mapping = aes(x = date, y = pre, ymin = low, ymax = up), alpha = 0.5, fill = 'gray') + geom_point(mapping = aes(x = date, y = obs), color = 'red') + theme(axis.text.x = element_blank(), axis.line = element_line(colour = "black",size = 1.3), panel.grid.minor  = element_blank(), panel.grid.major = element_blank(), axis.text.y = element_text(size = 14,family = 'sans'), axis.title.y.right = element_text(angle=90), axis.ticks = element_line(size = 1.3), panel.background = element_blank(), panel.border = element_rect(fill = NA,size = 1.3),legend.position = '',axis.title = element_text(family = 'sans',size = 16),plot.title = element_text(hjust = 0.5 , size = 18)) + xlab('') + ylab('') + 
  ggtitle('Venezuela')

cowplot::plot_grid(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,nrow = 6)
dev.off()
